---

version: "2.4"
services:
  morph:
    image: nspccdev/neo-go:0.95.3
    container_name: morph
    domainname: neofs
    hostname: morph
    network_mode: host
    restart: always
    stop_signal: SIGKILL
    environment:
      - ACC=/config/morph_chain.gz
    volumes:
      - ./vendor/morph_chain.gz:/config/morph_chain.gz
      - ./morph/protocol.privnet.yml:/config/protocol.privnet.yml
      - ./morph/node-wallet.json:/config/node-wallet.json
      - chain:/chain

  ir:
    image: nspccdev/neofs-aio:0.22.0-18-g0bcc505
    container_name: ir
    domainname: neofs
    hostname: ir
    network_mode: host
    restart: on-failure
    stop_signal: SIGKILL
    entrypoint: /bin/neofs-ir
    command: --config /config/config.yaml
    healthcheck:
      test: ["CMD-SHELL", "/bin/neofs-cli control healthcheck --ir -r localhost:16512 --binary-key /config/wallet.key | grep 'Health status: READY'"]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 20s
    volumes:
      - ./morph/node-wallet.json:/config/wallet.json
      - ./ir/wallet.key:/config/wallet.key
      - ./ir/config.yaml:/config/config.yaml
      - ./vendor/locode_db:/config/locode.db

  sn:
    image: nspccdev/neofs-aio:0.22.0-18-g0bcc505
    domainname: neofs
    hostname: sn
    container_name: sn
    restart: on-failure
    network_mode: host
    volumes:
      - ./sn/wallet.key:/config/wallet.key
      - ./sn/config.yaml:/config/config.yaml
      - data:/data
    stop_signal: SIGKILL
    entrypoint: /bin/neofs-node
    command: --config /config/config.yaml
    healthcheck:
      test: ["CMD-SHELL", "/bin/neofs-cli control healthcheck -r localhost:16513 --binary-key /config/wallet.key | grep 'Health status: READY'"]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 10s

  http_gate:
    image: nspccdev/neofs-http-gw:0.16.0
    domainname: neofs
    hostname: http_gate
    container_name: http_gate
    restart: on-failure
    network_mode: host
    volumes:
      - ./http/node.key:/node.key
    stop_signal: SIGKILL
    env_file: [ "./http/http.env" ]

volumes:
  data:
  chain:
